import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import LoginScreen from "./LoginScreen";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  // getServerSession : NextAuth function that lets you check if a user is logged in or not(authenticated) on the server side.

  // authOptions : These are your NextAuth configuration options (like providers, callbacks, secret, etc.)

  const session = await getServerSession(authOptions);

  // console.log({session})

  // If the user is logged in, this will contain their session data (name, email, image, etc.). If they are not logged in, it will be null.

  // rendering children on layout page where children is page.js (home page)

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* If you’re not logged in, you won’t be able to see the children — instead, the login screen will appear. */}

        {!session && <LoginScreen />}

        {/* If you’re logged in, you’ll see the children (the app content).*/}

        {session && (
          <div>
            <Navbar />
            {children}
          </div>
        )}
      </body>
    </html>
  );
}
